### ISSUE TITLE
Mystery Blocks

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#105]
To add the challenges that students can solve in the simulation, we are going to add “Mystery Blocks” in the Explore Screen: 

![image](https://github.com/phetsims/buoyancy/assets/26031501/13c9ac33-3ae1-4b1a-ade1-e37f8859a0da)

Mystery X: Volume = 3L, Mass =10.02 kg. (Material, Pyrite) 
Mystery Y: Volume = 1 L, Mass = 19.32 kg (Material = Gold)

Colors (both the same, as is the same used in pyrite/gold in the boat screen)

Add mystery objects need to add include the next changes in readouts and controls?

- Mass/Volume panel. The size of the panel is the same that always:
![image](https://github.com/phetsims/buoyancy/assets/26031501/6f635ff5-f0e7-423c-bd76-3d00861bad2c)

- Density and mass readout: a `?` symbol

![image](https://github.com/phetsims/buoyancy/assets/26031501/cd353ff2-be01-47a7-89ef-d9299f86ac0f)

**Comment by AgustinVallejo** [comment]
The above commit adds part of this functionality, specifically the Mass/Volume panel part

**Comment by AgustinVallejo** [comment]
Assigning back to @DianaTavares for review. A couple of things that are not exactly as requested but probably are good as they are right now:
1. Question mark is the same color as the density readout, red or blue, not black as it shows in the picture. 
2. Mystery X and Mystery Y appear before Custom because of the way that component is built. If we want Custom first, some refactoring would need to be made.

**Comment by DianaTavares** [comment]
Also, the mass readout needs to show `?` 
![image](https://github.com/phetsims/buoyancy/assets/26031501/03af048d-b323-47be-8ecd-e94780362c84)

**Comment by AgustinVallejo** [comment]
Added the '?', now I only need to make the string translatable and, with Diana's permission, will close.
