### ISSUE TITLE
% submerged algorithm doesn't work in 0 gravity

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#124]
From https://github.com/phetsims/buoyancy/issues/112, we are calculating percent submerged based on buoyancy force. This force is determined by gravity, so we don't have a way to get the submerged percentage when gravity is 0. Also this was causing https://github.com/phetsims/buoyancy/issues/123.

**Comment by DianaTavares** [comment]
Gravity cannot be 0 because that doesn't support the learning goals. When we designed this control, we thought that the minimal value of gravity can be 0.1 m/s2. If with this change, the issue is solved, good! If not, then we can use a bigger minimal value for gravity because its learning goal is small.

**Comment by DianaTavares** [comment]
It is not necessary that the minimal value of gravity to be zero. That doesn't support the learning goals. It can be 0.1 m/s2. If that solves the issue, good!! Or it can be bigger if it is necessary because the learning goal of that controls is small.

**Comment by zepumph** [comment]
I really like having a min gravity of 0.1. @AgustinVallejo want to update that and remove our workaround?

**Comment by AgustinVallejo** [comment]
I can! Really easy. However I have mixed feelings, since it's really interesting to show that at g=0 buoyant force does not apply, thus it being a direct consequence of water's weight, so I don't know how to feel about removing that feature. Obviously it would solve all our code problems in one sweep, but at what cost? I will apply the fix and propose to discuss this at design meeting, even if it means more work for us.

**Comment by DianaTavares** [comment]
I really think that is a distraction to have a g=0 m/s2. This can be discussed in a design meeting next week, but the idea of that control was that, even that g is related to the model of the buoyancy force, it is also in the weight force and in the same way! Then that doesn't modify the buoyant behavior of the block. A g=0 obviously affects the buoyancy and interaction with the block, but that goes beyond this simulation.

**Comment by AgustinVallejo** [comment]
That sounds convincing! Let's close :)
