### ISSUE TITLE
Review "fluid displaced" panel on the lab screen

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#129]
I added the fluid displaced panel over in https://github.com/phetsims/buoyancy/issues/113. And I think it is ready for review. Here is what it currently looks like: 

![image](https://github.com/phetsims/buoyancy/assets/6856943/89e37b49-1663-44fd-83f9-6a9364104a09)

Let me know what you think!

**Comment by DianaTavares** [comment]
wow, thanks @zepumph!! I have some comments:

1. the color of the fluid inside the beaker needs to be the same color as the fluid in the pool (because is the fluid displaced from the pool)
2. Related to the previous point, it is not just the color of the fluid, it needs to change its density to fit the ones in the poll, in that way, the buoyancy force has always the same value that the weight of that fluid displaced. 
![image](https://github.com/phetsims/buoyancy/assets/26031501/53f84cdf-35e4-4927-b739-71264ebfd167)

4. It is covering part of the ground, which is not ideal. I call for a design meeting to discuss this because one option is to make it smaller to fill bellow the ground, but I hope that with more designers' eyes, we can find a better idea.

**Comment by zepumph** [comment]
It stays on under the ground now.
![image](https://github.com/phetsims/buoyancy/assets/6856943/8959e627-070f-4415-958d-b7d90da77ac6)

**Comment by zepumph** [comment]
Ok, color and newton calculation should be fixed now too. Anything else for this panel right now?

**Comment by DianaTavares** [comment]
I looks amazing!! thanks @zepumph !!

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by zepumph** [comment]
Hmm. I think there was a caching problem here.  I'll investigate.
