### ISSUE TITLE
changes to the physics of a full boat

### ISSUE THREAD

**Issue by zepumph** [phetsims/buoyancy#142]
From design meeting and https://github.com/phetsims/buoyancy/issues/131

- [x] The mass of the full boat is just the hull mass (don't count the liquid.
- [x] When lifting a full boat out of the pool. It auto empties once high enough such that the gunnel (AKA gunwale) wouldn't be submerged again from the added liquid to the pool.

Also brought from #143 :

- [x] If every you would fill the boat a little, then instead fill it all the way up.
- [ ]  ~We need a delay in filling, such that it takes some amount of time/depth underwater in order to trigger a complete fill. This will help with bouncing when dropping the block into the boat from high up.~

**Comment by AgustinVallejo** [comment]
Most of this is implemented, but some questions arose along the way @DianaTavares :
- Currently, if you get the boat out of the water, it spills its contents out. Do you like the spilling out animation, or should it empty the contents instantly?
- I feel like items 3 and 4 are a bit contradictory and tricky to pull off at the same time. We want the boat to drown if it gets a bit of water inside, but not for some seconds. I'm not sure how to add the delay into the code. I'm either requesting to ignore the delay or asking for help.

**Comment by zepumph** [comment]
From discussion with @DianaTavares @AgustinVallejo @samreid @zepumph today, we will investigate:

* Faster animation speed
* ~Interrupt boat input when filling (not emptying)~
* General bug fixing and strange behavior
* Is half of height the right point to mark fill/empty behavior? (Maybe dynamic to the volume of the boat?)

**Comment by zepumph** [comment]
Alright. Everything has been implemented and we are quite happy with it. @DianaTavares please take things for a test drive. We decided not to interrupt the input ever, and instead only "spill out" the water when the boat is 90% out of the pool. This is working really well, and we can't find any other bugs.

**Comment by DianaTavares** [comment]
The interaction is amazing!! We only need to fix the vectors: 

![image](https://github.com/phetsims/buoyancy/assets/26031501/983c938e-b561-400b-ae7e-73905a14b369)

when the boat is in the fluid, the **buoyancy force** is only generated by the fluid displaced by its shell (in this case 10.88N, that it is 1.11 X 1 x 9.8, -> 1.11 because it is the fluid displaced only for the boat, 1 because in this case it is water and 1kg/L is its density, and 9.8 for the gravity value) 

The **weight** is only mass x g; in this case, the mass is 3, so the weight needs to be 29.4.

In that case, the sum of forces is zero (because the boat is in equilibrium): forces up (contact 18.51, + buoyancy 10.88) = to forces down (weight 29.4 N)

**Comment by DianaTavares** [comment]
and the boat shouldn't float when it is fluid inside it: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/62e3de87-1733-481f-b000-034dfc1644b9)

Please review fluids that have a density above the density of the Boat Body.

**Comment by DianaTavares** [comment]
We need to fix the forces:

![image](https://github.com/phetsims/buoyancy/assets/26031501/0d3094cc-0828-481b-b529-82619d933939)


when the boat is in the fluid, the buoyancy force is only generated by the fluid displaced by its shell (in this case 10.88N, that it is 1.11 X 1 x 9.8, -> 1.11 because it is the fluid displaced only for the boat, 1 because in this case it is water and 1kg/L is its density, and 9.8 for the gravity value)
The weight is only mass x g; in this case, the mass is 3, so the weight needs to be 29.4.
In that case, the sum of forces is zero (because the boat is in equilibrium): forces up (contact 18.51, + buoyancy 10.88) = to forces down (weight 29.4 N)

**Comment by zepumph** [comment]
I believe that a discussion with @jonathanolson will be the best path forward here. I'm worried about side effects if we try to hard code that there is "no" water in the boat basin.

**Comment by AgustinVallejo** [comment]
I think this is ready... 

@zepumph please double check the above code. Let's make sure this goes accordingly to what JO suggested.

@DianaTavares please review that this is what you were requesting.

**Comment by DianaTavares** [comment]
I look amazing!! Love it! 
Not sure if there is more stuff related to code in this issue, other way, you can close it.

**Comment by zepumph** [comment]
REVIEW:

* I added comments inline
* I wanted to make sure that our tolerance for when the boat was in the water was as desired. Is this really "out of the water"? 
![image](https://github.com/phetsims/buoyancy/assets/6856943/77c86837-0826-45c6-ab21-6527934263fc)


Feel free to close.

**Comment by DianaTavares** [comment]
I have to accept that I forgot for a moment of the fluid with a bigger density than the boat material. After analyzing your picture (and playing a little bit with the simulation), I think that we need more information for the students:
1) the volume inside the boat is 8.88...L, which explains that the boat's weight changes from 29,4 N to 287.25 N, as displayed in the picture. But calculating that is not going to be trivial for most students. 

![image](https://github.com/phetsims/buoyancy/assets/26031501/eebad421-efd9-4900-adff-8c4402fb1de2)

Then I go back to what you suggested some time ago, we need to tell them what the volume is inside the boat, and in that situation, I don't recommend a strange number as 8.888... L. Is possible to have something like 8.5? or at least 8.8? but the mass is 3 kg when the volume is 10?  (to maintain the initial state). 

2) the other number the user needs to make sense of is the buoyancy force (also 287.25 N).  I am not sure what the information gives to the students to make sense of that number.  The other screens have been showing students that they only need to make the operation: (density of the fluid)(gravity)(FLUID DISPLACED). The Fluid displaced is 9.9L in this case, not idea how the simulation can show them that value, or give them more information (from the pool) to deduce that value. From the  101.01 L I couldn't.  The true is that I don't know where that 101.01L came from.

**Comment by DianaTavares** [comment]
I added those new questions to a new issue #149
