### ISSUE TITLE
The dev version for interviews didn't open well in Edge browser 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#156]
This is the link to the dev version: https://phet-dev.colorado.edu/html/buoyancy/1.0.0-dev.8/phet/buoyancy_all_phet.html  

and in the Edge browser looks like this: 
![image](https://github.com/phetsims/buoyancy/assets/26031501/28a02347-bc74-42c1-a7c0-135df91b9025)

When the student changed to chrome, everything was ok!

**Comment by zepumph** [comment]
Looks like the student's copy of edge was not set up with WebGL enabled. I just ran on my copy of edge and it worked well. Perhaps there is a setting we didn't know about for edge that you have to set in certain computers.

**Comment by zepumph** [comment]
@DianaTavares, can you provide any more details about what device it was? Mac/Windows? OS version, etc?

**Comment by DianaTavares** [comment]
It is an assembled computer that had no brand. Also, changing the browser fixed it. If it's not a reproducible issue, I guess we can close this issue.

**Comment by zepumph** [comment]
I was able to reproduce this in edge when I toggled the hardware acceleration setting off. This is expected behavior, and the sim is working well when WebGL is not enabled. 

<img width="706" alt="image" src="https://github.com/phetsims/buoyancy/assets/6856943/0e6c5537-f8a6-4cd8-99e6-d854a68bb0ff">


You can also reproduce this by turning this setting off in chrome too. I'm thinking of closing this issue, but I want to confirm with @DianaTavares that there may want to be something in the teacher tips about the need of webgl to run this sim. Feel free to close.

**Comment by DianaTavares** [comment]
Yes! I will add it to the teacher tips, Thanks!!
