### ISSUE TITLE
"Playful" movement of the scale is distracting 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#158]
Now, with a small touch scales can go flying. Is possible to increase probably their fiction with the floor or something that makes it more difficult to move them by sliding?: 

![Untitled](https://github.com/phetsims/buoyancy/assets/26031501/6e098ac9-d0bc-4e86-b857-3d2a9455c572)

**Comment by zepumph** [comment]
The dev team has some thoughts about this design. We don't think it is limited to just the scale, and the mouse movement is always going to be "powerful" enough to make other objects fly, let's discuss.

**Comment by samreid** [comment]
@DianaTavares reported that during interviews, a client wanted to measure something, and accidentally bumped the scale. But since there is no clear way to address this without changing the physics of the rest of the system, it seems OK to close this issue. @DianaTavares reported it is not a significant problem. There is no way to know if the user accidentally hit the scale or purposefully moved the scale. So we will close the issue.
