### ISSUE TITLE
Planet X gravity value should be hidden

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#181]
During today's design meeting, we discovered a bug. When 'Planet X' is selected, the value is displayed. In this case, the `numberDisplay.visibleProperty` of the Gravity control should be `false`.
<img width="332" alt="image" src="https://github.com/phetsims/density-buoyancy-common/assets/8419308/3783a4fb-24df-4070-9477-cc3afaad9cbf">

This feature only appears in Buoyancy, so I believe this is the correct repo.

Assigning to the dev team.

**Comment by AgustinVallejo** [comment]
This was related to changes in https://github.com/phetsims/density-buoyancy-common/issues/239

Pushed a fix but I'm wondering something: Should the number display in mystery fluids and gravities NEVER show up? Because currently, it hides when you select planet X or density A/B, but via PhET-iO you can toggle it back on. I figured it could be used by an instructional designer to first raise the question for the gravity or density, and when students are done, display the number. But tossing back to @arouinfar for her feedback on this.

**Comment by arouinfar** [comment]
Back to @AgustinVallejo to use a gated `visibleProperty` so that the NumberDisplay can be permanently hidden with `numberDispalyVisibleProperty`.

**Comment by AgustinVallejo** [comment]
I think it was done right this time, back to Amy

**Comment by arouinfar** [comment]
Looks good on main, thanks @AgustinVallejo!
