### ISSUE TITLE
Some fluid's colors make difficult to appreciate the blocks in the pool

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#28]
- [x] The gradient color for the fluids gets very dark that not allow visualizing the blocks and scale inside the pool:

![image](https://user-images.githubusercontent.com/26031501/129637030-796bfc58-e753-4355-940e-36e13bfc9837.png)

I find nice the color for the less dense fluid. Then this is perfect for being the color associated with the minimin density. 

![image](https://user-images.githubusercontent.com/26031501/129637524-4374363c-21ff-4d0b-88b5-3524ac2accaa.png)

I think that the darkest color of the pool can go to this color (the one that we get when the Fluid density is 4). no sure what is the number of the color, but, can this be the color associated with the max density?
 
![image](https://user-images.githubusercontent.com/26031501/129637696-1f1daba4-7c87-40f9-a7ae-1f24768173f8.png)
 

- [x] Other colors that I find hard to see are honey:

![image](https://user-images.githubusercontent.com/26031501/129638472-a50ced78-964d-4f22-b408-6a18e5a4b433.png)

I modify its opacity in studio from 0.8 to 0.65 and I think that value has better visibility and still feeling like honey: 
![image](https://user-images.githubusercontent.com/26031501/129638408-fc45e3a6-034a-4157-8a74-07df5a6998c5.png)

- [x] The last color is mercury 
![image](https://user-images.githubusercontent.com/26031501/129638604-b0c0bd1e-95e9-4828-a054-9a93eedd37e3.png)

I also play with its opacity in studio, and I think that with an opacity of 0.8 is possible to identify the blocks insite ir 
![image](https://user-images.githubusercontent.com/26031501/129638790-dba01728-019e-476d-901c-dd8896ae6c26.png)

**Comment by jonathanolson** [comment]
Implemented, however I'm a bit concerned that mercury is made semi-transparent... it's pretty opaque. Perhaps that might give students the wrong impression? We haven't had other things be transparent so they can be seen through when it isn't physically plausible.

**Comment by DianaTavares** [comment]
I like how it looks but is an interesting point that the mercury is not transparent like now it is shown in the sim.  @arouinfar  and @ariel-phet. Can you give us your opinion about the colors of the fluids, and the contrast of the blocks under these fluids, especially the mercury? Thanks!!

**Comment by ariel-phet** [comment]
@DianaTavares @jonathanolson I would make a few comments:

1. I would consider making the custom fluid just go towards deeper blues. The kind of blackish fluid is a bit off-putting in my opinion. Or if you want to make sure it has a contrast with something like water, maybe choose something in the green or purple family or such. It just feels a bit dull to be blackish

2. For Mercury, if we want to use that substance, I think you don't have much choice but for it to be somewhat transparent. I think the options would be:
- Leave the transparency as is, and just accept that we are making a compromise because we need to be able to see the blocks within the fluid
- Make the fluid for Mercury fairly opaque and add some new representation (like a dotted outline of the block within the fluid), that seems like an expensive change at this point
- Choose a different high density fluid, or remove Mercury. Is having Mercury crucial to the learning goals since you have something like honey and the custom option?
- Call the substance something like "Mercury (90%)", so that it can be assumed to be some colloidal solution of Mercury. That might be a bit confusing because the density would be somewhat less than Mercury.

We might get some pushback on having a pool of Mercury anyhow since it is such a toxic substance. Teachers may not like that substance if they feel it could encourage students to try to see what happens with some Mercury in a thermometer for instance (I have gotten to play with Mercury and it is super fun, but yeah, dangerous)

**Comment by arouinfar** [comment]
> I would consider making the custom fluid just go towards deeper blues. The kind of blackish fluid is a bit off-putting in my opinion. Or if you want to make sure it has a contrast with something like water, maybe choose something in the green or purple family or such. It just feels a bit dull to be blackish

I agree. I am not a fan of the dark gray custom fluid. There are already two blue liquids (water, seawater) so I tested out a few colors on the violet/aqua sides of blue by changing the color of materialHoney in the [Color Editor](https://bayes.colorado.edu/dev/phettest/phetmarks/color-editor.html?sim=buoyancy&brand=phet). (I didn't see an option fo the custom material, otherwise I would have used that instead.) I think something along the lines of `rgb(0,30,255)` could work well. 

If we make this change, we need to bear in mind is that the custom liquid inside of the bottle uses the same color. There, I think the dark gray is a reasonable choice. I would suggest splitting up the color profile to use different colors for the custom pool liquid and the custom bottle liquid.

| Color | Full Saturation | Mid Saturation | Low Saturation |
| --- | --- | --- | --- |
| Current | <img width="435" alt="image" src="https://user-images.githubusercontent.com/8419308/159976715-a1d40a22-50a0-45fd-b6be-088b4503ae1c.png"> |  <img width="435" alt="image" src="https://user-images.githubusercontent.com/8419308/159976766-3b9b6a02-0b64-4fe1-bab7-5b0c2885a1fb.png"> | <img width="434" alt="image" src="https://user-images.githubusercontent.com/8419308/159976820-0fb0d460-30ec-4172-81e7-c0fec820452e.png"> |
| `rgb(50, 0, 255)` | <img width="441" alt="image" src="https://user-images.githubusercontent.com/8419308/159970630-e9023fbf-b1d2-4643-859e-cee7b793fe36.png"> | <img width="434" alt="image" src="https://user-images.githubusercontent.com/8419308/159974524-81d5bf81-112c-47a3-952b-d14b562b88b6.png"> | <img width="436" alt="image" src="https://user-images.githubusercontent.com/8419308/159974380-6041e359-ff51-43ea-b6ad-824fc6e28235.png"> |
| `rgb(0,30,255)` | <img width="435" alt="image" src="https://user-images.githubusercontent.com/8419308/159975154-acaca6ac-a4c4-43aa-9cf5-3cae5f9b515c.png"> | <img width="437" alt="image" src="https://user-images.githubusercontent.com/8419308/159975320-524d11ed-d6df-4e69-b0f4-d0a4ecef4bee.png"> | <img width="434" alt="image" src="https://user-images.githubusercontent.com/8419308/159975439-07aee568-de25-4624-a9b1-a888971fb6ad.png"> |
| `rgb(0, 255, 215)` | <img width="439" alt="image" src="https://user-images.githubusercontent.com/8419308/159975898-b5819c3f-d1e1-4c9c-afbf-eb5d04500ade.png"> | <img width="440" alt="image" src="https://user-images.githubusercontent.com/8419308/159975973-9b23fa35-6972-4a47-8264-3b61dc415a42.png"> | <img width="437" alt="image" src="https://user-images.githubusercontent.com/8419308/159976068-c77a1521-7d25-4bd8-8c07-f3786d100d1c.png"> |
| `rgb(0, 255, 180)` |  <img width="437" alt="image" src="https://user-images.githubusercontent.com/8419308/159976473-ef7e8654-b437-4018-8ee5-d4ad5855a79c.png"> |  <img width="440" alt="image" src="https://user-images.githubusercontent.com/8419308/159976546-afcc8392-e471-4f2b-8694-6db1a955b87d.png"> |  <img width="450" alt="image" src="https://user-images.githubusercontent.com/8419308/159976605-10a750fe-ea4c-4013-8171-da730ca024a3.png"> |

Here's seawater and water for comparison.
<img width="200" alt="image" src="https://user-images.githubusercontent.com/8419308/159979491-3f104485-1d95-48b2-bc3d-661fee3a5dfc.png"> <img width="200" alt="image" src="https://user-images.githubusercontent.com/8419308/159979542-d9c9bc41-3990-48d4-a78d-2946b6cfbf05.png">

> For Mercury, if we want to use that substance, I think you don't have much choice but for it to be somewhat transparent. I think the options would be:

I would agree. There's not much that can (or should) be done about Mercury's transparency. I would go with @ariel-phet's first option and do nothing. An explanation in the Teacher Tips should be sufficient.

> We might get some pushback on having a pool of Mercury anyhow since it is such a toxic substance. 

It's possible, but I would push back. The beauty of a PhET sim is that we can do things that aren't feasible (or safe) to do in a classroom lab, but are pedagogically useful. We could pre-emptively make a query parameter to hide mercury, though.

**Comment by DianaTavares** [comment]
Thanks, @arouinfar  and @Ariel for the inputs! 

- [ ] I agree that is better to change the black gradient color for the custom option, to a blue gradient. 
I play with @arouinfar  with some of the suggested color options and we select this one: 
![image](https://user-images.githubusercontent.com/26031501/159993054-1a37e4d5-7a09-425b-86e4-4c098b91083e.png)

It has very good contrast for color blindness and with the water. @jonathanolson  please change the gradient color of the custom fluid. Thanks! 

About Mercury, I agree with @arouinfar 's comment.  I also think that is nice to have a real and known super-dense fluid to play within the sim, where it is safe.  We leave mercury in the list of the options, with the gradient color that it has, and I will include a note in the teacher's tips about this.

**Comment by zepumph** [comment]
We discussed with @DianaTavares and it seems best to keep the opacity around .7 and just interpolate between whit and this new blue (which seems to be what @arouinfar did above). After solving https://github.com/phetsims/buoyancy/issues/81 we will come back to commit this logic. 

```diff
Subject: [PATCH] fdsafds
---
Index: js/common/model/Material.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/model/Material.ts b/js/common/model/Material.ts
--- a/js/common/model/Material.ts	(revision 739d32b464d503aa3d1003e5aa6eee903633898b)
+++ b/js/common/model/Material.ts	(date 1706644505722)
@@ -154,7 +154,7 @@
   public static getCustomLiquidColor( density: number ): ColorProperty {
     const lightness = Material.getCustomLightness( density * 0.25 );
 
-    return new ColorProperty( new Color( lightness, lightness, lightness, 0.8 * ( 1 - lightness / 255 ) ) );
+    return new ColorProperty( new Color( lightness, Utils.linear( 0, 255, 30, 255, lightness ), 255, .7 ) );
   }
 
   /**

**Comment by zepumph** [comment]
@DianaTavares, above @AgustinVallejo and I have changed the custom liquid color to go from white to blue. Please review and let us know what you think. If you want to tweak the light color (white) or the dark color (blue), you can edit them in the colors tool under the names "customLiquidDark" and "customLiquidLight". Please note that they won't update immediately though, you will need to change the density to get the new values. 

Feel free to close.

**Comment by zepumph** [comment]
@DianaTavares liked .6 opacity for the dark color. Closing
