### ISSUE TITLE
PhET-iO Design Review

### ISSUE THREAD

**Issue by arouinfar** [phetsims/buoyancy#51]
In last week's design check-in @jonathanolson indicated that the tree was ready for review. I'll use this issue to track the issues stemming from the design review.

**Comment by arouinfar** [comment]
@jonathanolson I've opened up issues for everything we discussed today. Please let me know if you have any questions!

**Comment by arouinfar** [comment]
From https://github.com/phetsims/density/issues/136#issuecomment-1223082878

- [x] When I resume the Buoyancy review, I should verify `volumeProperty` has the desired range and phetioReadOnly behavior. 
- [ ] https://github.com/phetsims/density-buoyancy-common/issues/224

**Comment by arouinfar** [comment]
Unassigning myself until work resumes on this sim.

**Comment by zepumph** [comment]
I think the best path for this issue is for @AgustinVallejo and I to take another pass through the sim to make sure that everything is looking acceptable to us (since it has been 2 years). The we should pass this to @arouinfar to give another (likely easier) tree review, especially since there are likely new patterns and preferences for instrumentation level. 

There are still a good number of PhET-iO issues for us to do from the last review, so I'll assign to myself, and we will let you know when it is a good time to review. 

UPDATE: I created https://github.com/phetsims/buoyancy/issues/86 also, for a more general pass.

**Comment by zepumph** [comment]
Note that I'm tagging some issues as ready for review as part of this issue, like https://github.com/phetsims/buoyancy/issues/58.

**Comment by zepumph** [comment]
UPDATE: NOTES AND DECISIONS ARE IN https://docs.google.com/document/d/18zd2SaoptzLLWRMm9S6OwHHQe-NpRfdHRICDiOplpEo/edit#heading=h.d16gusv6u2nf 

- [x] Devs are wondering about instrumentation level of the drag listeners. We created custom PhetioActions to wrap the mouse/touch dragging (https://github.com/phetsims/density-buoyancy-common/blob/7609258cae67e66a74a50ff16672a2f4183e9e10/js/common/view/DensityBuoyancyScreenView.ts#L107-L109). And over in https://github.com/phetsims/density-buoyancy-common/issues/98 we were wondering how important it is to instrument the keyboard drag listeners (one per massView). FYI Right now nothing in the mass view is instrumented.
- [ ] Review which instances of densityExpandedProperty should be instrumented.
- [ ] Should buoyancyDisplayOptionsPanel-> displayOptionsPanel?
- [ ] Do we want visibility properties (i.e. showBuoyancyForceProperty...) to be shown bundled in the model or in the view? 
- [ ] Should we change the visible properties names from showBuoyancyForceProperty to buoyancyForceVisibleProperty? Similar to how they are called in Kepler's.
- [ ] In Buoyancy Intro we removed an option called `adjustableMaterial` from the blocks, which was allowing to change the material of the blocks from studio. Like from wood to aluminum and such. Is that removal okay? Or do we want that feature in Buoyancy Intro screen?
- [ ] Instrument primaryMassProperty on the shapes screen? It isn't needed for state but may be better for studio. From https://github.com/phetsims/buoyancy/issues/160
- [ ] Nest all "primary" elements into its own section in the tree? (getting rid of `objects`)
- [ ] Should clients be able to change the properties of materials? For instance, the viscosity of wood is currently 0.001. Should clients be able to change that? `buoyancy.compareScreen.model.blockSets.sameDensity.block3A.materialProperty` and `buoyancy.shapesScreen.model.materialProperty`
- [ ] liquidViscosityProperty and liquidDensityProperty are derived from the material, and don't seem to need to be instrumented. Why are they here in phet-io? SR and MK think it is over instrumentation.
- [ ] Name checkboxes to match the model Property, or the text on screen. For example: showGravityForceProperty. Should it be `showGravityForceCheckbox` (currently there) or `gravityCheckbox` (convention used in PDL)?
- [ ] As above, also blocksRadioButtonGroup, in which the panel text is "Blocks", and the underlying Property is `blockSetProperty`.
- [ ] A conversation about when to instrument Text instances seems nice. In PDL and Buoyancy we don't seem to have a way to hide panel titles, but you can auto select the strings and edit them (even to an empty string for an awkward-layout hiding).
- [x] Strings that don't auto select: density/%-submerged accordion boxes, and force/mass labels on objects. This is because those texts are on dynamic instances, and create/dispose as model masses are shown/hid.. We think that is ok and it would be expensive to change. Please check this box.
- [ ] On all Compare screens: Do we want to keep the `toggleNode.elements` under `BlocksValueControlPanel`? It introduces two levels of nesting.
- [ ] Why is `massNumberControl.numberControlMassProperty` featured? Same for volume. Should they be featured, a doc ought to be written for them.
- [ ] Should we address buggyness in the common code components and their phet-io behavior? For example, you can remove the slider's track without problem.
- [ ] When hiding the pool mass height slider, the pool mass is no longer draggable. Is this OK? Should it be documented?
- [ ] Do we want panels with sliders to be named `*ControlPanel` or would just panel suffice?

**Comment by brent-phet** [comment]
@zepumph @AgustinVallejo Please note the reference to Buoyancy in this `joist` issue. https://github.com/phetsims/joist/issues/961

**Comment by zepumph** [comment]
- [x] Ensure use of `simulationPreferences` instead of `simPreferences`

**Comment by AgustinVallejo** [comment]
We're moving all the comments in https://github.com/phetsims/buoyancy/issues/51#issuecomment-1979357490 towards the following google doc:
https://docs.google.com/document/d/18zd2SaoptzLLWRMm9S6OwHHQe-NpRfdHRICDiOplpEo/edit

**Comment by arouinfar** [comment]
Design review is complete for both Buoyancy and Buoyancy: Basics. The remaining work is tracked in other issues including:
*  https://github.com/phetsims/density-buoyancy-common/issues/325 
*  https://github.com/phetsims/buoyancy/issues/176
*  https://github.com/phetsims/density/issues/200
