### ISSUE TITLE
Modifications in the Fluids list in intro screen, and the Fluid Density control in the other screens

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#54]
**INTRO SCREEN** 
- [x] The fluids that are available in the intro screen have a very similar density that is not easy to see the effect of the fluid on the Buoyancy force. The design team decides to modify them to the next list:

Gasoline (with a density of 0.68 kg/L)
Water
Seawater
Honey  (with a density of 1.44 kg7L)

We add Gasoline and Honey and delete Oil.

**FLUID DENSITY CONTROL on the other screens** 
 
- [x] add Oil to the combobox of the Fluid Density control. Oil has a density of 0.92 kg/L

- [x] For the mystery fluid densities, change the text  Density X, Y, etc., to Fluid A and B for the Explore screen, Fluid C and D for the Shapers Screen, and Fluid E and F for the Applications screen. 

- [x] The text that is displayed when a mystery fluid is selected is very long. Change if jus to "What is the fluid density?" 
![image](https://user-images.githubusercontent.com/26031501/170144753-b4d70ff3-1616-4ab2-915d-303f7046cbb9.png)

- [x] Right now, when the user selects first a mystery fluid density (for example Density X), and after that selects the Custom option, the slider shows the value of the Density X, taking away all the mystery! modify this behavior. When the user selects a mystery fluid density and the next custom is selected, the slider needs to go the value that was previous to the selection of the mystery density. The same behavior that the [Lab screen of Masses and Sprignd](https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_en.html?screens=4) in the case of the Gravity control. 

![denistyX](https://user-images.githubusercontent.com/26031501/170145740-aea34f37-2f6e-456c-a2b1-cc8268458067.gif)

- [x] Change the mystery fluid densities for real densities of fluids. This is the new list of values:

- Explore Screen: Fluid A (3.10 kg/L), Fluid B (0.79 kg/L)
- Shapes screen: Fluid C (0.49 kg/L), Fluid D (2.89 kg/L)
- Explore Screen Fluid E (1.26 kg/L), Fluid F (6.44 kg/L).

**Comment by jonathanolson** [comment]
Implemented all of this in the above commits. The "don't show hidden info" change also applies to the gravity control (seemed beneficial, and it used the same code). Can you see how it looks?

**Comment by DianaTavares** [comment]
All the changes are amazing! but, two of the mystery densities (A and F) are a little far from the desired value:
![image](https://user-images.githubusercontent.com/26031501/174452745-9f8ced66-bc1c-46bc-9112-e63e0d2830f5.png)

@jonathanolson, can you fix it?

**Comment by zepumph** [comment]
@DianaTavares will double check the above calculations and report back with steps to change.

**Comment by DianaTavares** [comment]
Yes, the values of the mystery fluids A n F need to be modified to march the values in the previous table. 
A= 3.1
F = 6.44

**Comment by zepumph** [comment]
Very nice! This will require some investigation because the intended densities are just what you recommended:

https://github.com/phetsims/density-buoyancy-common/blob/ccd027c1337a2d2c419eda41a60cc48f71b26114/js/common/model/Material.ts#L346
https://github.com/phetsims/density-buoyancy-common/blob/ccd027c1337a2d2c419eda41a60cc48f71b26114/js/common/model/Material.ts#L391

I'll need to come back to this.

**Comment by zepumph** [comment]
This will involve tracking the calculation into the model to understand where the error is coming from. I'd like to team up for that.

**Comment by zepumph** [comment]
Hello! Again this seems almost identical to the error in calculation over in https://github.com/phetsims/buoyancy/issues/87#issuecomment-1942058726. It seems to be entirely based on how the water level displayed (in liters) is only showing two decimal places. Here are a couple examples:

For mystery F, we chose concrete:
Mass of the bottle: `31.6` (31.5 from concrete)
Total water level displayed: `104.91`
Density calculated from displayed:  `6.435845213849287`
Actual water level: `4.906848813118813`
Density calculated from actual level: `6.439978324890534`

So the mystery fluid density is supposed to be 6.44, and we find that the extra couple of decimal places (4-5 total instead of 2) makes a huge difference in this calculation. 

I'm not sure if we want to do nothing, as some variation from rounding displays helps to show the "real world" nature of these calculations. Also, perhaps, similar to https://github.com/phetsims/buoyancy/issues/87#issuecomment-1942058726, we may want to add more decimal places for important readouts. Let me know what you'd like to do.

**Comment by zepumph** [comment]
@DianaTavares and I discussed this, and we feel like the rounding error is acceptable, and doesn't need any improvements. We talked about making most readouts on the shapes/application screens read to three decimal places, but decided it wasn't worth the trouble. Closing
