### ISSUE TITLE
When the “Average” value matches the Fluid Density, makes that the bottle behave as a natural buoyancy. 

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/buoyancy#87]
Try to match the Average Density of the bottle to the density of the water (1 kg/L), and the bottle still moving down or up. Like the next picture that shows a bottle with a density of 1 kg/L and still part of it floating in the surface. 

![image](https://github.com/phetsims/buoyancy/assets/26031501/22f23eb2-4362-4516-9bfc-01503c4177e2)

Why? 
High-dense materials have the same volume with a big range of masses. For example, for Mercury, the range of mass from 9.86 kg to 9.98 kg (12 clicks to the mass buttons), will display a 0.73L of volume. Several of these mass values and that volume will display a Density of 1 kg/L for the bottle, but is not exactly that! Then the bottle, in some cases still floating or sinking. 

Idea:
When the Average value matches the fluid density, behaves as “natural buoyancy” (in this case, something close to 1, make it 1! because this is water, but do the same for the other fluids densities)

**Comment by AgustinVallejo** [comment]
We think this is the current behavior, it's just that the Density readout is rounding up the numbers. But with the forces diagram you can actually achieve "natural bouyancy":

![image](https://github.com/phetsims/buoyancy/assets/37052186/9d9711fd-51fb-49dc-a34e-fbb65bcb4e22)

In the diagram you see how even though the density says 1.00, the forces are unbalanced. If you play with the Mass Number Control you can achieve equality in the forces and have the bottle stand still.

**Comment by zepumph** [comment]
>When the Average value matches the fluid density, behaves as “natural buoyancy” (in this case, something close to 1, make it 1! because this is water, but do the same for the other fluids densities)

To me this issue just seems like a rounding convenience, and it is nice that the force arrows show that. If we increase the mass to 9.90kg then the force values do actually cancel out. If we are really worried about this being confusing, then we could add a decimal place to the density display. That would likely solve this problem. But @AgustinVallejo mentioned that three decimal places makes things more confusing since it is easy to confuse with 1000kg (instead of 1.000).  Also I wonder if we need decimal place consistency, and that it is important that all readouts are currently just to 2 decimal spots.

Also, if you ever want the actual density of the bottle while working on this issue, you can type this in the console:

`phet.joist.sim.screens[4].model.masses[0].materialProperty.value.density`

With all this in mind, I think @AgustinVallejo and I recommend doing nothing for this issue. Let us know what you think!

**Comment by zepumph** [comment]
@DianaTavares and I discussed this, and we feel like the rounding error is acceptable, and doesn't need any improvements. We talked about making most readouts on the shapes/application screens read to three decimal places, but decided it wasn't worth the trouble. Closing
